version: "3.7"
services:
  
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: "exit 0"
    container_name: local-db

volumes:
  postgres-data:
    driver: local
