{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: default
   
{{- end }}

# ---
# {{- if .Values.serviceAccount.create}}
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: {{ .Values.clusterRole.name}}
# rules:
# - apiGroups:
#   {{ .Values.clusterRole.rules.apiGroups}}
#   resources: {{.Values.clusterRole.rules.resources}}
#   verbs:
#   {{- range .Values.clusterRole.rules.verbs }}
#     {{ . }}
#   {{- end }}
  
# {{- end }}

# ---
# {{ if .Values.serviceAccount.create}}
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: {{ .Values.clusterRoleBinding.name}}
# roleRef:
#   kind: ClusterRole
#   name: {{ .Values.clusterRoleBinding.roleRef.name}}
#   apiGroup: rbac.authorization.k8s.io
# subjects:
#   {{ .Values.clusterRoleBinding.subjects}}

# {{end}}

