apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - autoscale.yaml
  - config.yaml
  - serviceAccount.yaml
  - storageclass.yaml
  - ingress.yaml
  - secret.yaml
  - pvc.yaml
