apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: local
spec:
  capacity:
    storage: 5Gi  # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage  # You'll need to create this StorageClass separately
  local:
    path: /home/dell/Desktop/devops2  # Path on the host machine where data will be stored
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - your-node-name  # Replace with the name of your Kubernetes node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage  # Should match the storageClassName in the PV
  resources:
    requests:
      storage: 5Gi  # Match the storage size with the PV capacity
