apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-backend
  namespace: sock-shop
  labels:
    name: jaeger-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-backend
  template:
    metadata:
      labels:
        app: jaeger-backend
    spec:
      containers:
        - name: jaeger-backend
          image: techmatt/jaeger-backend:v1
          imagePullPolicy: Always
          ports:
            - name: backend-port
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "50m"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
    name: jaeger-backend
    namespace: sock-shop
spec:
    selector:
        app: jaegeer-backend
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000